### ISSUE TITLE
Error when adding a new entry into `Blocks` field

### ISSUE THREAD

**Issue by markusritschel** [igk1972/grav-plugin-admin-frontmatter-yaml#1]
When I try to add another entry to the `Blocks` field in the plugin preferences, GRAV throws an error:
```
Error: Call to undefined method Grav\Common\Data\Data::header()
```

**Comment by igk1972** [comment]
Hi Markus,
Please write version Grav, Grav Admin. And your config admin-frontmatter-yaml.

**Comment by igk1972** [comment]
Maybe these examples will help you.

![2019-12-21 в 0 56 44](https://user-images.githubusercontent.com/54089/71295679-0554e780-238e-11ea-8381-f2d9bc214733.png)

**Comment by markusritschel** [comment]
Hi igk1972,

Sorry for my late answer and thanks a lot for your reply, including the screenshots.
My Grav specs are as follows:
**Grav:** v1.6.19
**Grav Admin:** v1.9.12
**admin-frontmatter.yaml:**
```
enabled: true
blocks: title,metadata,taxonomy
```
---
If I get this right, one must specify those frontmatter keys under `blocks` in the *config/admin-frontmatter-yaml.yaml* file, which are supposed to be non-shared (i.e. localized). Is that correct? So, everything, which should be language-specific, must be in `blocks`?

Is it possible to switch this behavior? Such that only those keys I want to have shared between languages are mentioned in the configuration file?

Thanks a lot in advance!
Cheers,
Markus

**Comment by igk1972** [comment]
This is correct.
Youre must specify frontmatter keys under blocks in the config/admin-frontmatter-yaml.yaml file, which are supposed to be (non-shared). 

Behavior Is not switch (now). Maybe in future...

Have a nice day!

**Comment by markusritschel** [comment]
Thanks for this info!
Have a nice day, too!
